/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuriyanto_lab_lutisjvm_Lutis */

#ifndef _Included_com_wuriyanto_lab_lutisjvm_Lutis
#define _Included_com_wuriyanto_lab_lutisjvm_Lutis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuriyanto_lab_lutisjvm_Lutis
 * Method:    powerN
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wuriyanto_lab_lutisjvm_Lutis_powerN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wuriyanto_lab_lutisjvm_Lutis
 * Method:    rotateImageN
 * Signature: (D[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wuriyanto_lab_lutisjvm_Lutis_rotateImageN
  (JNIEnv *, jobject, jdouble, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
